# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-05 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecieveData',
            fields=[
                ('primary_field', models.IntegerField(primary_key=True, serialize=False)),
                ('first_field', models.CharField(blank=True, max_length=20, null=True)),
                ('second_field', models.CharField(blank=True, max_length=20, null=True)),
                ('third_field', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
